### ISSUE TITLE
Code4App 是一个移动平台的代码库。

### ISSUE THREAD

**Issue by kengsir** [tingxins/TXScrollLabelView#1]
hi 觉得您的文章写得不错,您可以授权文章发表在 http://www.code4app.com  上面么？期待您的回复！

Code4App 是一个移动平台的代码库。
Code4App 收集了 iOS 平台近 5 千份代码。
我们不需要造轮子，我们应该将我们的聪明才智发挥到其他更 牛逼 的创意上去。

**Comment by tingxins** [comment]
可以的^_^

目前还是初级版本，不妥之处还有待修复。
