### ISSUE TITLE
数据源为数组时，怎么更新数据源数组？？ 请教一下

### ISSUE THREAD

**Issue by LemonChao** [tingxins/TXScrollLabelView#13]

**Comment by tingxins** [comment]
当前 Pod 版本暂不支持，下一版本将做优化。如要更新数据源数组，可以先尝试修改.m 中的 scrollArray Or scrollTexts 属性。

**Comment by LemonChao** [comment]
如你所述，问题已解决，多谢了

**Comment by 1277393484** [comment]
你好！请教下怎么更新数据源数组，scrollArray Or scrollTexts 作为公开属性吗？
