### ISSUE TITLE
CocoaPods搜索不到 

### ISSUE THREAD

**Issue by dengxingwen** [tingxins/TXScrollLabelView#18]
CocoaPods搜索不到 ，下载源码 拖入文件夹import也搜不到文件

**Comment by tingxins** [comment]
可以的，链接：![TXScrollLabelView](http://cocoadocs.org/docsets/TXScrollLabelView/1.3.2/)。建议你更新一下本地的CocoaPods仓库，或者删除~/Library/Caches/CocoaPods/search_index.json 文件，再进行尝试。
