### ISSUE TITLE
在从左向右设置的scrollLabel中设置速率,没有改变,一直是一个速率

### ISSUE THREAD

**Issue by AnGuoli** [tingxins/TXScrollLabelView#2]
TXScrollLabelView *scrollLabelView = [TXScrollLabelView tx_setScrollTitle:scrollTitle scrollType:TXScrollLabelViewTypeLeftRight scrollVelocity:2.0 options:UIViewAnimationOptionTransitionFlipFromTop];

改变scrollVelocity 比如是10.0 , 0.1 滚动的速率都没有变化
scrollLabelView.tx_scrollVelocity = 10.0; 这样修改也没用

**Comment by tingxins** [comment]
恩，是的，目前版本中的velocity暂时只生效于TXScrollLabelViewType_FlipNoCle类型，新版本正在改进，会尽快修复此问题
