### ISSUE TITLE
滚动有点卡顿

### ISSUE THREAD

**Issue by gaoshilei** [tingxins/TXScrollLabelView#3]
滚动有点卡顿，是否可以考虑缩短定时器更新UI的时间间隔来消除这种不流畅的感觉呢？

**Comment by tingxins** [comment]
恩，好的，后续版本更新会跟进解决此问题

**Comment by SilenceZhou** [comment]
把NSTimer换成 CADisplayLink 可以完美解决该问题 ，我的项目就是在这个基础上进行优化的
