### ISSUE TITLE
文本颜色设置不生效

### ISSUE THREAD

**Issue by dongbobo1992** [tingxins/TXScrollLabelView#5]
![image](https://cloud.githubusercontent.com/assets/7426508/20508185/cc15b4c2-b09a-11e6-82de-0d915ab86774.png)
![image](https://cloud.githubusercontent.com/assets/7426508/20508306/9f16f070-b09b-11e6-94e7-bd146254d1f8.png)
![image](https://cloud.githubusercontent.com/assets/7426508/20508195/dcbdd58e-b09a-11e6-9a98-23453454c6d0.png)
![image](https://cloud.githubusercontent.com/assets/7426508/20508295/863889e2-b09b-11e6-8073-4c8b14a9a923.png)

属性名和方法名好像没对上？
好像是新加的属性，没有对应的实现

**Comment by tingxins** [comment]
恩，这个Bug将在下个节点被fix掉，先用 `tx_scrollTitleColor` 代替着
