### ISSUE TITLE
很好,可以添加上点击方法么?表的拖动会影响么?

### ISSUE THREAD

**Issue by Gx952743985** [tingxins/TXScrollLabelView#6]
希望添加上点击方法

**Comment by tingxins** [comment]
是的，拖拽表视图不会对其产生影响，GitHub上的版本已增加点击回调，待会更新一下Cocoapods 上的版本

**Comment by Gx952743985** [comment]
谢谢,刚刚没看到

**Comment by tingxins** [comment]
@Gx952743985 CocoaPods 暂时更新至 v1.1.3 ^_^（更多优化正在ing）
